import {StyleSheet} from 'react-native'

import {
  DECK_CARD_HEIGHT,
  DECK_CARD_RADIUS,
  DECK_GUTTER,
  DECK_OVERLAP,
  DECK_SECONDARY_TOP,
  DECK_STAGGER,
  DECK_THIRD_TOP,
} from './helpers'

// Icon inset that puts a 20pt icon's center on the quarter disc's centroid.
const DECK_CORNER_ICON_INSET = Math.round(
  (4 * DECK_OVERLAP) / (3 * Math.PI) - 10,
)

export const styles = StyleSheet.create({
  topChrome: {
    elevation: 20,
    zIndex: 20,
  },
  // Zero-height, full-width rows that web fixes to the viewport's top and
  // bottom edges to carry the floating buttons (see MemesScreen).
  webFixedRow: {
    height: 0,
    left: 0,
    right: 0,
    zIndex: 25,
  },
  // Layout.Content centers children on web but applies contentContainerStyle
  // outside the column, so the board adds its own inner gutter there.
  webColumnPadding: {
    paddingHorizontal: 16,
  },
  contentShell: {
    flex: 1,
    zIndex: 0,
  },
  contentContainer: {
    gap: 16,
    padding: 16,
    paddingBottom: 48,
    paddingTop: 8,
  },
  contentContainerUnderChrome: {
    paddingTop: 64,
  },
  deckContentShell: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingBottom: 0,
    paddingHorizontal: 0,
    paddingTop: 8,
  },
  headerSearchContent: {
    flex: 1,
    paddingLeft: 4,
  },
  floatingChrome: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingHorizontal: 26,
    position: 'absolute',
    right: 0,
    top: 18,
    zIndex: 25,
  },
  floatingButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  floatingButtonActive: {
    backgroundColor: '#1E293B',
  },
  floatingButtonIcon: {
    color: '#ffffff',
  },
  boardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  loadMoreButton: {
    alignItems: 'center',
    borderRadius: 8,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  fabPosition: {
    bottom: 28,
    position: 'absolute',
    right: 20,
  },
  fab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  cardShell: {
    width: '100%',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 4},
    elevation: 3,
  },
  cardVisual: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'space-between',
    overflow: 'hidden',
    padding: 18,
  },
  mediaVisual: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  mediaVisualOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  cardBadgeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardVisualBottom: {
    gap: 10,
  },
  partyInsignia: {
    borderColor: 'rgba(15, 23, 42, 0.24)',
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.12,
    shadowRadius: 4,
    width: 32,
  },
  cardTitle: {
    color: '#121212',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 32,
    width: '88%',
  },
  cardTitleOnImage: {
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 3,
  },
  cardBody: {
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  cardMeta: {
    fontSize: 14,
    fontWeight: '700',
  },
  cardSubmeta: {
    fontSize: 14,
    lineHeight: 19,
  },
  actionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  actionButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    height: 34,
    paddingHorizontal: 12,
  },
  actionButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  deckStage: {
    minHeight: DECK_SECONDARY_TOP + DECK_CARD_HEIGHT,
    position: 'relative',
    width: '100%',
  },
  deckBoundaryNotice: {
    alignSelf: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.86)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    position: 'absolute',
    top: -4,
    zIndex: 20,
  },
  deckBoundaryNoticeText: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: '700',
  },
  deckEndCard: {
    alignItems: 'center',
    borderRadius: 12,
    borderStyle: 'dashed',
    borderWidth: 1,
    height: DECK_CARD_HEIGHT * 0.4,
    justifyContent: 'center',
    left: DECK_GUTTER + DECK_STAGGER,
    paddingHorizontal: 24,
    position: 'absolute',
    right: DECK_GUTTER,
    top: DECK_CARD_HEIGHT + 12,
    zIndex: 1,
  },
  deckEndTitle: {
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  deckEndBody: {
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
    textAlign: 'center',
  },
  deckSlot: {
    borderRadius: DECK_CARD_RADIUS,
    height: DECK_CARD_HEIGHT,
    position: 'absolute',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },
  deckSlotRaised: {
    elevation: 8,
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.28,
    shadowRadius: 18,
  },
  deckSlotInner: {
    borderRadius: DECK_CARD_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    overflow: 'hidden',
  },
  deckSlotCurrent: {
    left: DECK_GUTTER,
    right: DECK_GUTTER + DECK_STAGGER,
    top: 0,
  },
  deckSlotPrev: {
    left: DECK_GUTTER,
    right: DECK_GUTTER + DECK_STAGGER,
    top: 0,
    zIndex: 6,
  },
  deckSlotNext: {
    left: DECK_GUTTER + DECK_STAGGER,
    right: DECK_GUTTER,
    top: DECK_SECONDARY_TOP,
  },
  deckSlotThird: {
    left: DECK_GUTTER + DECK_STAGGER,
    right: DECK_GUTTER,
    top: DECK_THIRD_TOP,
    zIndex: 1,
  },
  deckCardShell: {
    height: DECK_CARD_HEIGHT,
  },
  deckVisual: {
    flex: 1,
    justifyContent: 'flex-end',
    // Keep the title and pills above the overlap so they stay readable when
    // the card below is raised over this one.
    paddingBottom: DECK_OVERLAP + 14,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  deckVisualBottom: {
    gap: 10,
  },
  deckTitle: {
    color: '#121212',
    fontSize: 25,
    fontWeight: '800',
    lineHeight: 29,
  },
  deckTitleOnImage: {
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 3,
  },
  deckDim: {
    ...StyleSheet.absoluteFill,
  },
  deckBandLayer: {
    ...StyleSheet.absoluteFill,
    zIndex: 10,
  },
  deckBand: {
    borderBottomRightRadius: DECK_CARD_RADIUS,
    borderTopLeftRadius: DECK_CARD_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    elevation: 12,
    height: DECK_OVERLAP,
    left: DECK_GUTTER + DECK_STAGGER,
    overflow: 'hidden',
    position: 'absolute',
    right: DECK_GUTTER + DECK_STAGGER,
    top: DECK_SECONDARY_TOP,
    zIndex: 10,
  },
  // Quarter discs anchored on the two card corners inside the band. The icon
  // sits on the disc's visual center, 4r/3π in from the corner.
  deckBandCorner: {
    height: DECK_OVERLAP,
    position: 'absolute',
    width: DECK_OVERLAP,
  },
  deckBandCornerStart: {
    alignItems: 'flex-start',
    borderBottomRightRadius: DECK_OVERLAP,
    borderTopLeftRadius: DECK_CARD_RADIUS,
    justifyContent: 'flex-start',
    left: 0,
    padding: DECK_CORNER_ICON_INSET,
    top: 0,
  },
  deckBandCornerEnd: {
    alignItems: 'flex-end',
    borderBottomRightRadius: DECK_CARD_RADIUS,
    borderTopLeftRadius: DECK_OVERLAP,
    bottom: 0,
    justifyContent: 'flex-end',
    padding: DECK_CORNER_ICON_INSET,
    right: 0,
  },
  deckBandComments: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 2,
  },
  deckBandCommentsText: {
    fontSize: 15,
    fontWeight: '600',
  },
  deckBandCenter: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    // Just clear of the quarter discs, which leaves room for votes and
    // comments on 375pt-wide phones.
    marginHorizontal: DECK_OVERLAP * 0.42,
  },
  searchSuggest: {
    ...StyleSheet.absoluteFill,
    zIndex: 30,
  },
  searchSuggestContent: {
    paddingBottom: 48,
    paddingTop: 4,
  },
  searchSuggestRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  searchMemeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  searchMemeThumb: {
    borderRadius: 8,
    height: 44,
    overflow: 'hidden',
    width: 44,
  },
  searchChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 16,
  },
  searchChip: {
    alignItems: 'center',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    maxWidth: '100%',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  commentChip: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    height: 38,
    justifyContent: 'center',
    minWidth: 68,
    paddingHorizontal: 12,
  },
  commentChipFloating: {
    minWidth: 68,
  },
  commentChipCompact: {
    height: 26,
    minWidth: 0,
    paddingHorizontal: 8,
  },
  commentChipText: {
    fontSize: 13,
    fontWeight: '800',
  },
  metaPillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    maxWidth: '100%',
    minHeight: 28,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  metaPillOnImage: {
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  metaPillText: {
    fontSize: 12,
    fontWeight: '700',
  },
  metaPillTextOnImage: {
    color: '#ffffff',
  },
  deckCardPressable: {
    flex: 1,
  },
  viewerRoot: {
    backgroundColor: '#000',
    flex: 1,
  },
  viewerHeader: {
    left: 0,
    paddingHorizontal: 12,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  viewerBackButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  viewerFooter: {
    bottom: 0,
    left: 0,
    paddingTop: 48,
    position: 'absolute',
    right: 0,
  },
  viewerControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 20,
  },
  viewerControl: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  emptyState: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 28,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyDescription: {
    fontSize: 15,
    lineHeight: 21,
    maxWidth: 320,
    textAlign: 'center',
  },
})
