import {StyleSheet} from 'react-native'

import {DECK_CARD_HEIGHT, DECK_SECONDARY_TOP, DECK_THIRD_TOP} from './helpers'

export const styles = StyleSheet.create({
  topChrome: {
    elevation: 20,
    zIndex: 20,
  },
  contentShell: {
    flex: 1,
    zIndex: 0,
  },
  contentContainer: {
    gap: 16,
    padding: 16,
    paddingBottom: 48,
    paddingTop: 8,
  },
  deckContentShell: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingBottom: 0,
    paddingHorizontal: 0,
    paddingTop: 20,
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  headerSearchContent: {
    paddingRight: 8,
    width: '100%',
  },
  headerSearchButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerViewToggleButton: {
    alignItems: 'center',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerViewToggleButtonActive: {
    backgroundColor: '#1E293B',
  },
  viewToggleButton: {
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  viewToggleButtonActive: {
    backgroundColor: '#1E293B',
  },
  boardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  loadMoreButton: {
    alignItems: 'center',
    borderRadius: 8,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  cardShell: {
    width: '100%',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 4},
    elevation: 3,
  },
  cardVisual: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'space-between',
    overflow: 'hidden',
    padding: 18,
  },
  mediaVisual: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  mediaVisualOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  cardBadgeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardVisualBottom: {
    gap: 10,
  },
  partyInsignia: {
    borderColor: 'rgba(15, 23, 42, 0.24)',
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.12,
    shadowRadius: 4,
    width: 32,
  },
  cardTitle: {
    color: '#121212',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 32,
    width: '88%',
  },
  cardTitleOnImage: {
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 3,
  },
  cardBody: {
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  cardMeta: {
    fontSize: 14,
    fontWeight: '700',
  },
  cardSubmeta: {
    fontSize: 14,
    lineHeight: 19,
  },
  actionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  actionButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    height: 34,
    paddingHorizontal: 12,
  },
  actionButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  deckStage: {
    marginTop: 8,
    minHeight: DECK_CARD_HEIGHT + DECK_SECONDARY_TOP + 100,
    position: 'relative',
    width: '100%',
  },
  deckBoundaryNotice: {
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.86)',
    borderRadius: 8,
    left: '50%',
    paddingHorizontal: 14,
    paddingVertical: 8,
    position: 'absolute',
    top: -4,
    transform: [{translateX: -92}],
    zIndex: 20,
  },
  deckBoundaryNoticeText: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: '700',
  },
  deckEndCard: {
    backgroundColor: '#0F172A',
    borderRadius: 8,
    left: 34,
    paddingHorizontal: 16,
    paddingVertical: 14,
    position: 'absolute',
    right: 34,
    top: DECK_SECONDARY_TOP + DECK_CARD_HEIGHT + 14,
    zIndex: 2,
  },
  deckEndTitle: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '800',
  },
  deckEndBody: {
    color: '#CBD5E1',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  deckPrimary: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 1,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 52,
    top: 0,
    zIndex: 3,
  },
  deckPrevIncoming: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 1,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 34,
    top: 0,
    zIndex: 5,
  },
  deckSecondary: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 1,
    left: 52,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: DECK_SECONDARY_TOP,
    zIndex: 2,
  },
  deckHidden: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 1,
    left: 52,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: DECK_THIRD_TOP,
    zIndex: 1,
  },
  deckCardShell: {
    minHeight: DECK_CARD_HEIGHT,
    position: 'relative',
  },
  deckVisual: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'space-between',
    padding: 15,
  },
  deckVisualBottom: {
    gap: 8,
    paddingTop: 8,
  },
  deckBody: {
    overflow: 'hidden',
    position: 'relative',
  },
  deckBodyContent: {
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    gap: 2,
    paddingBottom: 16,
    paddingHorizontal: 16,
    paddingTop: 8,
    zIndex: 1,
  },
  deckBodyGlassTail: {
    display: 'none',
  },
  deckInfoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  deckSubmeta: {
    flex: 1,
  },
  deckTitle: {
    color: '#121212',
    fontSize: 25,
    fontWeight: '800',
    lineHeight: 28,
    width: '86%',
  },
  deckTitleOnImage: {
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 3,
  },
  deckCommandCenter: {
    alignItems: 'flex-start',
    alignSelf: 'center',
    position: 'absolute',
    top: DECK_SECONDARY_TOP - 44,
    zIndex: 10,
  },
  deckCommandCenterZone: {
    alignItems: 'center',
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
  },
  commentChip: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    height: 38,
    justifyContent: 'center',
    minWidth: 68,
    paddingHorizontal: 12,
  },
  commentChipFloating: {
    minWidth: 68,
  },
  commentChipCompact: {
    height: 26,
    minWidth: 0,
    paddingHorizontal: 8,
  },
  commentChipText: {
    fontSize: 13,
    fontWeight: '800',
  },
  metaPillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    maxWidth: '100%',
    minHeight: 28,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  metaPillOnImage: {
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  metaPillText: {
    fontSize: 12,
    fontWeight: '700',
  },
  metaPillTextOnImage: {
    color: '#ffffff',
  },
  deckCardPressable: {
    flex: 1,
  },
  expandedModalOverlay: {
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  expandedModalDismiss: {
    flex: 1,
  },
  expandedModalSheet: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingBottom: 34,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  expandedHandle: {
    alignSelf: 'center',
    borderRadius: 8,
    height: 5,
    marginBottom: 14,
    width: 44,
  },
  expandedVisual: {
    borderRadius: 8,
    justifyContent: 'space-between',
    minHeight: 236,
    padding: 18,
  },
  expandedBody: {
    gap: 10,
    paddingHorizontal: 4,
    paddingTop: 16,
  },
  emptyState: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 28,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyDescription: {
    fontSize: 15,
    lineHeight: 21,
    maxWidth: 320,
    textAlign: 'center',
  },
})
