{
 "title": "Sonar",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "op_kind",
    "label": "Operation Kind",
    "query": {
     "query": "label_values(sonar_ops_processed_total,kind)"
    }
   },
   {
    "name": "box",
    "label": "Sonar Host",
    "query": {
     "query": "label_values(indigo_repo_stream_bytes_total{job=\"sonar\"},box)"
    }
   },
   { "name": "socket", "label": "Socket", "query": { "query": "label_values(socket_url)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(sonar_events_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Event Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(rate(sonar_events_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"}[$__rate_interval])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Event Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(sonar_events_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"}[$__rate_interval]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(rate(sonar_events_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"}[$__rate_interval] offset 1d))",
     "legendFormat": "1 Day Ago"
    },
    {
     "expr": "sum(rate(sonar_events_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"}[$__rate_interval] offset 1w))",
     "legendFormat": "1 Week Ago"
    },
    {
     "expr": "sum(rate(sonar_events_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"}[$__rate_interval] offset 4w))",
     "legendFormat": "4 Weeks Ago"
    }
   ]
  },
  {
   "title": "Record Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(rate(sonar_records_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"}[$__rate_interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firehose Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sonar_last_evt_created_evt_processed_gap{box=~\"${box}\",socket_url=~\"${socket}\"}",
     "legendFormat": "Since Event Creation"
    },
    {
     "expr": "sonar_last_record_created_evt_processed_gap{box=~\"${box}\",socket_url=~\"${socket}\"}",
     "legendFormat": "Since Record Creation"
    }
   ]
  },
  {
   "title": "Operation Kind Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sonar_ops_processed_total{box=~\"${box}\",socket_url=~\"${socket}\"}[$__range])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"sonar\", box=~\"${box}\",instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Record Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sonar_records_processed_total{box=~\"${box}\",socket_url=~\"${socket}\", action=\"create\"}[$__range])) by (record_type)",
     "legendFormat": "{{record_type}}"
    }
   ]
  },
  {
   "title": "Socket Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(indigo_repo_stream_bytes_total{box=~\"${box}\",instance=~\"${instance}\"}[$__rate_interval])) by (instance) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"sonar\", box=~\"${box}\",instance=~\"${instance}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU per Event",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"sonar\", box=~\"${box}\",instance=~\"${instance}\"}[$__rate_interval])) by (instance) / sum(rate(sonar_events_processed_total{box=~\"${box}\",instance=~\"${instance}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "CPU Seconds per Event"
    }
   ]
  },
  {
   "title": "Profiles Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sonar_ops_processed_total{kind=~\"create\",socket_url=~\"wss://bsky.network/xrpc/com.atproto.sync.subscribeRepos\", op_path=\"app.bsky.actor.profile\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(rate(sonar_ops_processed_total{kind=~\"${op_kind}\", box=~\"${box}\",socket_url=~\"${socket}\"}[$__rate_interval])) by (op_path, kind) > 0",
     "legendFormat": "{{kind}} {{op_path}}"
    }
   ]
  }
 ]
}